### ISSUE TITLE
Why not license under Apache 2.0?

### ISSUE THREAD

**Issue by olljanat** [KatharaFramework/NetworkPlugin#11]
Is there some particular reason why this is licensed under GPL-3.0 instead of Apache 2.0 which Docker is using?

There is some boring limitations/unexpected behaviors in Docker default bridge driver when it comes to IPv6 support (discussed in here https://github.com/docker/docs/issues/19556 ) and I would like to create alternative for it but keep codebase compatible with Docker so maybe some day it might get included to it without need to use plugin.

**Comment by Skazza94** [comment]
Hi @olljanat,
thanks for the issue.

Initially we put GPL-3.0 as it is the same of the Kathará main repository.

But, we understand that now the Network Plugin can also be used standalone, and the GPL-3.0 might not be the best license. We are internally verifying if we can change the License to Apache 2.0, checking if there are problems with the dependencies that we rely on (for example VDE).

I will reply to the issue as soon as I have a response.

Cheers,
Mariano.

**Comment by olljanat** [comment]
Thanks and for clarification. I'm only using bridge driver from this repository so you probably can solve this with folder level license in case VDE requires GPL.

**Comment by olljanat** [comment]
FYI, my plugin can be now found from https://github.com/olljanat/docker-bgp-lb in case someone reading this is interested.

**Comment by Skazza94** [comment]
Hi @olljanat,
sorry for the late reply.

We switched the License to Apache 2.0, I will close this issue.
